// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: protos/Notification.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Details       string                 `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	MainUid       string                 `protobuf:"bytes,3,opt,name=main_uid,json=mainUid,proto3" json:"main_uid,omitempty"`
	TargetId      string                 `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	IsRead        bool                   `protobuf:"varint,5,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	User          *User                  `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationRequest) Reset() {
	*x = NotificationRequest{}
	mi := &file_protos_Notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequest) ProtoMessage() {}

func (x *NotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_Notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequest.ProtoReflect.Descriptor instead.
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return file_protos_Notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *NotificationRequest) GetMainUid() string {
	if x != nil {
		return x.MainUid
	}
	return ""
}

func (x *NotificationRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *NotificationRequest) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *NotificationRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NotificationRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_protos_Notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_protos_Notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_protos_Notification_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

var File_protos_Notification_proto protoreflect.FileDescriptor

const file_protos_Notification_proto_rawDesc = "" +
	"\n" +
	"\x19protos/Notification.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x01\n" +
	"\x13NotificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\adetails\x18\x02 \x01(\tR\adetails\x12\x19\n" +
	"\bmain_uid\x18\x03 \x01(\tR\amainUid\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\tR\btargetId\x12\x17\n" +
	"\ais_read\x18\x05 \x01(\bR\x06isRead\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x19\n" +
	"\x04user\x18\a \x01(\v2\x05.UserR\x04user\"2\n" +
	"\x04User\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar2W\n" +
	"\x13NotificationService\x12@\n" +
	"\x10SendNotification\x12\x14.NotificationRequest\x1a\x16.google.protobuf.EmptyB\tZ\a/protosb\x06proto3"

var (
	file_protos_Notification_proto_rawDescOnce sync.Once
	file_protos_Notification_proto_rawDescData []byte
)

func file_protos_Notification_proto_rawDescGZIP() []byte {
	file_protos_Notification_proto_rawDescOnce.Do(func() {
		file_protos_Notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_Notification_proto_rawDesc), len(file_protos_Notification_proto_rawDesc)))
	})
	return file_protos_Notification_proto_rawDescData
}

var file_protos_Notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_Notification_proto_goTypes = []any{
	(*NotificationRequest)(nil),   // 0: NotificationRequest
	(*User)(nil),                  // 1: User
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 3: google.protobuf.Empty
}
var file_protos_Notification_proto_depIdxs = []int32{
	2, // 0: NotificationRequest.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: NotificationRequest.user:type_name -> User
	0, // 2: NotificationService.SendNotification:input_type -> NotificationRequest
	3, // 3: NotificationService.SendNotification:output_type -> google.protobuf.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_Notification_proto_init() }
func file_protos_Notification_proto_init() {
	if File_protos_Notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_Notification_proto_rawDesc), len(file_protos_Notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_Notification_proto_goTypes,
		DependencyIndexes: file_protos_Notification_proto_depIdxs,
		MessageInfos:      file_protos_Notification_proto_msgTypes,
	}.Build()
	File_protos_Notification_proto = out.File
	file_protos_Notification_proto_goTypes = nil
	file_protos_Notification_proto_depIdxs = nil
}
