// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: protos/Chat.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_protos_Chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_Chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_protos_Chat_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MessageRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_protos_Chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_Chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_protos_Chat_proto_rawDescGZIP(), []int{1}
}

func (x *MessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        string                 `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_protos_Chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_protos_Chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_protos_Chat_proto_rawDescGZIP(), []int{2}
}

func (x *UserID) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

type UsersIDsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIdsLists  []*UserIDsList         `protobuf:"bytes,1,rep,name=user_ids_lists,json=userIdsLists,proto3" json:"user_ids_lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersIDsListResponse) Reset() {
	*x = UsersIDsListResponse{}
	mi := &file_protos_Chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersIDsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersIDsListResponse) ProtoMessage() {}

func (x *UsersIDsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_Chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersIDsListResponse.ProtoReflect.Descriptor instead.
func (*UsersIDsListResponse) Descriptor() ([]byte, []int) {
	return file_protos_Chat_proto_rawDescGZIP(), []int{3}
}

func (x *UsersIDsListResponse) GetUserIdsLists() []*UserIDsList {
	if x != nil {
		return x.UserIdsLists
	}
	return nil
}

type UserIDsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIdsList   []string               `protobuf:"bytes,1,rep,name=user_ids_list,json=userIdsList,proto3" json:"user_ids_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDsList) Reset() {
	*x = UserIDsList{}
	mi := &file_protos_Chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDsList) ProtoMessage() {}

func (x *UserIDsList) ProtoReflect() protoreflect.Message {
	mi := &file_protos_Chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDsList.ProtoReflect.Descriptor instead.
func (*UserIDsList) Descriptor() ([]byte, []int) {
	return file_protos_Chat_proto_rawDescGZIP(), []int{4}
}

func (x *UserIDsList) GetUserIdsList() []string {
	if x != nil {
		return x.UserIdsList
	}
	return nil
}

var File_protos_Chat_proto protoreflect.FileDescriptor

const file_protos_Chat_proto_rawDesc = "" +
	"\n" +
	"\x11protos/Chat.proto\"^\n" +
	"\x0eMessageRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x03 \x01(\tR\breceiver\"+\n" +
	"\x0fMessageResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\" \n" +
	"\x06UserID\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\tR\x06userid\"J\n" +
	"\x14UsersIDsListResponse\x122\n" +
	"\x0euser_ids_lists\x18\x01 \x03(\v2\f.UserIDsListR\fuserIdsLists\"1\n" +
	"\vUserIDsList\x12\"\n" +
	"\ruser_ids_list\x18\x01 \x03(\tR\vuserIdsList2\x88\x01\n" +
	"\x13RealtimeChatService\x12=\n" +
	"\x19GetUserFollowingFollowers\x12\a.UserID\x1a\x15.UsersIDsListResponse\"\x00\x122\n" +
	"\vSendMessage\x12\x0f.MessageRequest\x1a\x10.MessageResponse\"\x00B\tZ\a/protosb\x06proto3"

var (
	file_protos_Chat_proto_rawDescOnce sync.Once
	file_protos_Chat_proto_rawDescData []byte
)

func file_protos_Chat_proto_rawDescGZIP() []byte {
	file_protos_Chat_proto_rawDescOnce.Do(func() {
		file_protos_Chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_Chat_proto_rawDesc), len(file_protos_Chat_proto_rawDesc)))
	})
	return file_protos_Chat_proto_rawDescData
}

var file_protos_Chat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_Chat_proto_goTypes = []any{
	(*MessageRequest)(nil),       // 0: MessageRequest
	(*MessageResponse)(nil),      // 1: MessageResponse
	(*UserID)(nil),               // 2: UserID
	(*UsersIDsListResponse)(nil), // 3: UsersIDsListResponse
	(*UserIDsList)(nil),          // 4: UserIDsList
}
var file_protos_Chat_proto_depIdxs = []int32{
	4, // 0: UsersIDsListResponse.user_ids_lists:type_name -> UserIDsList
	2, // 1: RealtimeChatService.GetUserFollowingFollowers:input_type -> UserID
	0, // 2: RealtimeChatService.SendMessage:input_type -> MessageRequest
	3, // 3: RealtimeChatService.GetUserFollowingFollowers:output_type -> UsersIDsListResponse
	1, // 4: RealtimeChatService.SendMessage:output_type -> MessageResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_Chat_proto_init() }
func file_protos_Chat_proto_init() {
	if File_protos_Chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_Chat_proto_rawDesc), len(file_protos_Chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_Chat_proto_goTypes,
		DependencyIndexes: file_protos_Chat_proto_depIdxs,
		MessageInfos:      file_protos_Chat_proto_msgTypes,
	}.Build()
	File_protos_Chat_proto = out.File
	file_protos_Chat_proto_goTypes = nil
	file_protos_Chat_proto_depIdxs = nil
}
