name: CI/CD Pipeline

on:
  push:
    branches: [main, auto-testing]
  pull_request:
    branches: [main, auto-testing]

jobs:
  backend-tests:
    uses: ./.github/workflows/be-tests.yml
    secrets: inherit

  integration-frotend-tests:
    uses: ./.github/workflows/integration-test.yml
    needs: backend-tests
    secrets: inherit

  deploy-to-dockerhub:
    uses: ./.github/workflows/docker-deployment.yml
    needs: integration-frotend-tests
    secrets: inherit
