name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    uses: ./.github/workflows/docker-deployment.yml
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
